### ISSUE TITLE
Improvement: Make time property optional

### ISSUE THREAD

**Issue by carroe** [d-velop/grafana-odata-datasource#2]
A user in the OData newsgroup wants to use the plugin without time property.

See: https://groups.google.com/g/odata-discussion/c/KwnOSWpBGu4

Currently the use of the time property is mandatory.

**Comment by ezhov-evgeny** [comment]
+1

**Comment by T1000-Cyberd** [comment]
Make time property optional please

**Comment by jannikbend** [comment]
Hi, the changes have not been released yet. 
We cant name an exact release date but hope/expect it to happen before the christmas days.

**Comment by thomann061** [comment]
+1

**Comment by T1000-Cyberd** [comment]
Is this completed? When will you guys release it?

**Comment by enessolakoglu** [comment]
Hello, when is the planned release date for the upcoming version ?

**Comment by jannikbend** [comment]
Hi, sorry it took us so long, but we finally released the new version yesterday. Today it went through grafana's review process and is now generally available.
